version: '2'
services:
    refdatagenerator-app:
        image: refdatagenerator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://refdatagenerator-mysql:3306/refdatagenerator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    refdatagenerator-mysql:
        extends:
            file: mysql.yml
            service: refdatagenerator-mysql
